= Browser User Interface for Teragrep

This project contains the web-based user interface for Teragrep. It’s used with https://github.com/teragrep/zep_01[zep_01] which is the server-side for Teragrep, but you can use it with your own back-end service as well.

Teragrep is a server-based software with a web interface. It has data collection features comparable to the leading central log management products, and its analytics features are powered by Apache Spark.

== Features

* Notebook based interface
* Querying
* Result data visualization
* Collaborative editing
* Versioning in notebooks
* Notebook run scheduler
* Report view
* Light and dark modes
* Sessions, login, logout

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== How to Set-Up 

=== Requirements

For installation, you need at least https://github.com/teragrep/zep_01[zep_01] to run the back-end. 

For the local developing, you need the following:

* https://nodejs.org/en[Node.js]
* https://docs.npmjs.com/[npm]

Optionally, you can use https://github.com/teragrep/adp_01[adp_01] to fully replicate the back-end locally. The commands descriped in the local development guide are for using the fake-server which is included in ajs_01.

=== Installation

1. Add https://teragrep.github.io/pkg_01/[pkg_01] repository
2. Run
+
```
dnf install com.teragrep-ajs_01
```

=== Local development

Build commands are described in package.json.

1. Install yarn and required dependencies
+
```
$ npm install -g yarn
$ yarn install
```
2. Run the front-end application
+
```
$ yarn run dev
```
+
or run the development server
+
```
$ yarn run fakeserver
```
+
or run both instances parallel
+
```
$ yarn run both
```

== Custom Theme

You can customize the color scheme of Teregrep to match your own color palette or brand identity. Read more https://docs.teragrep.com/doc_01/1.0.0/administrator%20guide/custom-theme.html[here].

== Contributing

You can involve yourself with our project by https://github.com/teragrep/ajs_01/issues/new/choose[opening an issue] or submitting a pull request. 

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories. 
